#ifndef SI4464_H
#define SI4464_H

#define uint8_t unsigned char
#define int16_t short

typedef struct 
{
    U8 FREQ_CONTROL_INTE;
    U8 FREQ_CONTROL_FRAC_2;
    U8 FREQ_CONTROL_FRAC_1;
    U8 FREQ_CONTROL_FRAC_0;
    U8 FREQ_CONTROL_CHANNEL_STEP_SIZE_1;
    U8 FREQ_CONTROL_CHANNEL_STEP_SIZE_0;
    U8 FREQ_CONTROL_W_SIZE;
    U8 FREQ_CONTROL_VCOCNT_RX_ADJ;
    U8 GLOBAL_XO_TUNE;
    U8 GLOBAL_CLK_CFG;
    U8 GLOBAL_CONFIG;
    U8 PREAMBLE_TX_LENGTH;
    U8 PREAMBLE_CONFIG_STD_1;
    U8 PREAMBLE_CONFIG_NSTD;
    U8 PREAMBLE_CONFIG_STD_2;
    U8 PREAMBLE_CONFIG;
    U8 PREAMBLE_PATTERN_31_24;
    U8 PREAMBLE_PATTERN_23_16;
    U8 PREAMBLE_PATTERN_15_8;
    U8 PREAMBLE_PATTERN_7_0;
    U8 SYNC_CONFIG;
    U8 SYNC_BITS_31_24;
    U8 SYNC_BITS_23_16;
    U8 SYNC_BITS_15_8;
    U8 SYNC_BITS_7_0;
    U8 PKT_CRC_CONFIG;
    U8 PKT_CONFIG1;
    U8 PKT_LEN;
    U8 PKT_LEN_FIELD_SOURCE;
    U8 PKT_LEN_ADJUST;
    U8 PKT_FIELD_1_LENGTH_12_8;
    U8 PKT_FIELD_1_LENGTH_7_0;
    U8 PKT_FIELD_1_CONFIG;
    U8 PKT_FIELD_1_CRC_CONFIG;
    U8 PKT_FIELD_2_LENGTH_12_8;
    U8 PKT_FIELD_2_LENGTH_7_0;
    U8 PKT_FIELD_2_CONFIG;
    U8 PKT_FIELD_2_CRC_CONFIG;
    U8 PKT_FIELD_3_LENGTH_12_8;
    U8 PKT_FIELD_3_LENGTH_7_0;
    U8 PKT_FIELD_3_CONFIG;
    U8 PKT_FIELD_3_CRC_CONFIG;
    U8 PKT_FIELD_4_LENGTH_12_8;
    U8 PKT_FIELD_4_LENGTH_7_0;
    U8 PKT_FIELD_4_CONFIG;
    U8 PKT_FIELD_4_CRC_CONFIG;
    U8 PKT_FIELD_5_LENGTH_12_8;
    U8 PKT_FIELD_5_LENGTH_7_0;
    U8 PKT_FIELD_5_CONFIG;
    U8 PKT_FIELD_5_CRC_CONFIG;
    U8 PKT_RX_FIELD_1_LENGTH_12_8;
    U8 PKT_RX_FIELD_1_LENGTH_7_0;
    U8 PKT_RX_FIELD_1_CONFIG;
    U8 PKT_RX_FIELD_1_CRC_CONFIG;
    U8 PKT_RX_FIELD_2_LENGTH_12_8;
    U8 PKT_RX_FIELD_2_LENGTH_7_0;
    U8 PKT_RX_FIELD_2_CONFIG;
    U8 PKT_RX_FIELD_2_CRC_CONFIG;
    U8 PKT_RX_FIELD_3_LENGTH_12_8;
    U8 PKT_RX_FIELD_3_LENGTH_7_0;
    U8 PKT_RX_FIELD_3_CONFIG;
    U8 PKT_RX_FIELD_3_CRC_CONFIG;
    U8 PKT_RX_FIELD_4_LENGTH_12_8;
    U8 PKT_RX_FIELD_4_LENGTH_7_0;
    U8 PKT_RX_FIELD_4_CONFIG;
    U8 PKT_RX_FIELD_4_CRC_CONFIG;
    U8 PKT_RX_FIELD_5_LENGTH_12_8;
    U8 PKT_RX_FIELD_5_LENGTH_7_0;
    U8 PKT_RX_FIELD_5_CONFIG;
    U8 PKT_RX_FIELD_5_CRC_CONFIG;
    U8 MODEM_MOD_TYPE;
    U8 MODEM_MAP_CONTROL;
    U8 MODEM_DSM_CONTROL;
    U8 MODEM_DATA_RATE_2;
    U8 MODEM_DATA_RATE_1;
    U8 MODEM_DATA_RATE_0;
    U8 MODEM_TX_NCO_MODE_3;
    U8 MODEM_TX_NCO_MODE_2;
    U8 MODEM_TX_NCO_MODE_1;
    U8 MODEM_TX_NCO_MODE_0;
    U8 MODEM_FREQ_DEV_2;
    U8 MODEM_FREQ_DEV_1;
    U8 MODEM_FREQ_DEV_0;
    U8 MODEM_MDM_CTRL;
    U8 MODEM_IF_CONTROL;
    U8 MODEM_IF_FREQ_2;
    U8 MODEM_IF_FREQ_1;
    U8 MODEM_IF_FREQ_0;
    U8 MODEM_DECIMATION_CFG1;
    U8 MODEM_DECIMATION_CFG0;
    U8 MODEM_AFC_GEAR;
    U8 MODEM_AFC_WAIT;
    U8 MODEM_AFC_GAIN_1;
    U8 MODEM_AFC_GAIN_0;
    U8 MODEM_AFC_LIMITER_1;
    U8 MODEM_AFC_LIMITER_0;
    U8 MODEM_AFC_MISC;
    U8 MODEM_AFC_ZIFOFF;
    U8 MODEM_CLKGEN_BAND;
    U8 MODEM_RSSI_CONTROL;
    U8 MODEM_TX_RAMP_DELAY;
    U8 MODEM_BCR_OSR_1;
    U8 MODEM_BCR_OSR_0;
    U8 MODEM_BCR_NCO_OFFSET_2;
    U8 MODEM_BCR_NCO_OFFSET_1;
    U8 MODEM_BCR_NCO_OFFSET_0;
    U8 MODEM_BCR_GAIN_1;
    U8 MODEM_BCR_GAIN_0;
    U8 MODEM_BCR_GEAR;
    U8 MODEM_BCR_MISC1;
    U8 MODEM_BCR_MISC0;
    U8 PA_MODE;
    U8 PA_PWR_LVL;
    U8 PA_BIAS_CLKDUTY;
    U8 PA_TC;
    U8 SYNTH_PFDCP_CPFF;
    U8 SYNTH_PFDCP_CPINT;
    U8 SYNTH_VCO_KV;
    U8 SYNTH_LPFILT3;
    U8 SYNTH_LPFILT2;
    U8 SYNTH_LPFILT1;
    U8 SYNTH_LPFILT0;
    U8 MODEM_CHFLT_RX1_CHFLT_COE13;
    U8 MODEM_CHFLT_RX1_CHFLT_COE12;
    U8 MODEM_CHFLT_RX1_CHFLT_COE11;
    U8 MODEM_CHFLT_RX1_CHFLT_COE10;
    U8 MODEM_CHFLT_RX1_CHFLT_COE9;
    U8 MODEM_CHFLT_RX1_CHFLT_COE8;
    U8 MODEM_CHFLT_RX1_CHFLT_COE7;
    U8 MODEM_CHFLT_RX1_CHFLT_COE6;
    U8 MODEM_CHFLT_RX1_CHFLT_COE5;
    U8 MODEM_CHFLT_RX1_CHFLT_COE4;
    U8 MODEM_CHFLT_RX1_CHFLT_COE3;
    U8 MODEM_CHFLT_RX1_CHFLT_COE2;
    U8 MODEM_CHFLT_RX1_CHFLT_COE1;
    U8 MODEM_CHFLT_RX1_CHFLT_COE0;
    U8 MODEM_CHFLT_RX1_CHFLT_COEM0;
    U8 MODEM_CHFLT_RX1_CHFLT_COEM1;
    U8 MODEM_CHFLT_RX1_CHFLT_COEM2;
    U8 MODEM_CHFLT_RX1_CHFLT_COEM3;
    U8 MODEM_CHFLT_RX2_CHFLT_COE13;
    U8 MODEM_CHFLT_RX2_CHFLT_COE12;
    U8 MODEM_CHFLT_RX2_CHFLT_COE11;
    U8 MODEM_CHFLT_RX2_CHFLT_COE10;
    U8 MODEM_CHFLT_RX2_CHFLT_COE9;
    U8 MODEM_CHFLT_RX2_CHFLT_COE8;
    U8 MODEM_CHFLT_RX2_CHFLT_COE7;
    U8 MODEM_CHFLT_RX2_CHFLT_COE6;
    U8 MODEM_CHFLT_RX2_CHFLT_COE5;
    U8 MODEM_CHFLT_RX2_CHFLT_COE4;
    U8 MODEM_CHFLT_RX2_CHFLT_COE3;
    U8 MODEM_CHFLT_RX2_CHFLT_COE2;
    U8 MODEM_CHFLT_RX2_CHFLT_COE1;
    U8 MODEM_CHFLT_RX2_CHFLT_COE0;
    U8 MODEM_CHFLT_RX2_CHFLT_COEM0;
    U8 MODEM_CHFLT_RX2_CHFLT_COEM1;
    U8 MODEM_CHFLT_RX2_CHFLT_COEM2;
    U8 MODEM_CHFLT_RX2_CHFLT_COEM3;
} RFParametersType;


typedef void (*si4461_callback_t) (uint8_t* buf, uint8_t len, uint8_t lqi, int16_t rssi);

typedef struct 
{
    int TotRx;
    int TotTx;
    int TotCrcErr;
} RFStatusType;

extern RFStatusType RFStatus;

void setupSI4461(void);

uint8_t initSI4461(void* parameters);
uint8_t sendPacketSI4461(uint8_t* buf, uint8_t len);
uint8_t getRssiSI4461(int16_t* rssi);
void powerdownSI4461(void);
void powerupSI4461(void);
uint8_t getRxStatusSI4461(uint8_t* status);
uint8_t receivePacketSI4461(uint8_t* buf, uint8_t* len, uint8_t* lqi, int16_t* rssi);
void calibrateSI4461(void);

void setCallbackSI4461(si4461_callback_t cb);

int setTransmitPowerSI4461(int dbm);

#endif
